spring:
  mail:
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  rabbitmq:
    host: goodreads
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 5s
          multiplier: 1
        missing-queues-fatal: false

rabbit:
  brokers:
    - exchange: send.mail
      routingKey: route.mail.sender
      queue: queue.mail
      deadLetter: true
server:
  port: 8081